[package]
name = "MioPractice"
version = "0.1.0"
authors = ["KennethZhang <zjhken01@163.com>"]

[dependencies]
mio = "0.6"
log = "0.4.4"
simple_logger = "0.5"
slab = "0.4.0"

[profile.release]
lto = true